name = "spinmacho-login-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmacho-login.com"
HMAC_KEY = "e1ad9778d6aca4fd8059dca9fd6614aae7c2ed1f61d35171909c229c666dca83"
COOKIE_NAME = "l54"
PLAY_PATH = "explore"
BUTTON_ID = "p6a3c757b98b5720ca018c6efae29daca"
GATE_SALT = "c4cfd00fac6fac61"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "rdbp"
CTA_SELECTOR = ".play-button"
